extends Node


var upgrade_choices = {
	
	"regular_arm1": {
		"item_name" : "regular_arms",
		"type" : "arm",
		"icon" : "Arms/regular_arms.png",
		"displayname" : "Regular Arms",
		"details" : "A pair of fists that can punch",
		"prerequisite": [],
		"part_level" : 1,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_arm2": {
		"item_name" : "regular_arms",
		"type" : "arm",
		"icon" : "Arms/regular_arms.png",
		"displayname" : "Regular Arms",
		"details" : "A pair of fists that can punch",
		"prerequisite" : ["regular_arm1"],
		"part_level" : 2,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_arm3": {
		"item_name" : "regular_arms",
		"type" : "arm",
		"icon" : "Arms/regular_arms.png",
		"displayname" : "Regular Arms",
		"details" : "A pair of fists that can punch",
		"prerequisite" : ["regular_arm2"],
		"part_level" : 3,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"plague_arm1": {
		"item_name" : "plague_arms",
		"type" : "arm",
		"icon" : "Arms/plague_arms.png",
		"displayname" : "Plague Arms",
		"details" : "Arms of a plague doctor holding a scythe",
		"prerequisite" : [],
		"part_level" : 1,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"plague_arm2": {
		"item_name" : "plague_arms",
		"type" : "arm",
		"icon" : "Arms/plague_arms.png",
		"displayname" : "Plague Arms",
		"details" : "Arms of a plague doctor holding a scythe",
		"prerequisite" : ["plague_arm1"],
		"part_level" : 2,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"plague_arm3": {
		"item_name" : "plague_arms",
		"type" : "arm",
		"icon" : "Arms/plague_arms.png",
		"displayname" : "Plague Arms",
		"details" : "Arms of a plague doctor holding a scythe",
		"prerequisite" : ["plague_arm2"],
		"part_level" : 3,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_chest1": {
		"item_name" : "regular_chest",
		"type" : "chest",
		"icon" : "Chest/regular_chest.png",
		"displayname" : "Regular Chest",
		"details" : "Good old regular blue T-shirt",
		"prerequisite" : [],
		"part_level" : 1,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_chest2": {
		"item_name" : "regular_chest",
		"type" : "chest",
		"icon" : "Chest/regular_chest.png",
		"displayname" : "Regular Chest",
		"details" : "Good old regular blue T-shirt",
		"prerequisite" : ["regular_chest1"],
		"part_level" : 2,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_chest3": {
		"item_name" : "regular_chest",
		"type" : "chest",
		"icon" : "Chest/regular_chest.png",
		"displayname" : "Regular Chest",
		"details" : "Good old regular blue T-shirt",
		"prerequisite" : ["regular_chest2"],
		"part_level" : 3,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_leg1": {
		"item_name" : "regular_legs",
		"type" : "leg",
		"icon" : "Legs/regular_legs.png",
		"displayname" : "Regular Legs",
		"details" : "Normal person's legs",
		"prerequisite" : [],
		"part_level" : 1,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_leg2": {
		"item_name" : "regular_legs",
		"type" : "leg",
		"icon" : "Legs/regular_legs.png",
		"displayname" : "Regular Legs",
		"details" : "Normal person's legs",
		"prerequisite" : ["regular_leg1"],
		"part_level" : 2,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
	"regular_leg3": {
		"item_name" : "regular_legs",
		"type" : "leg",
		"icon" : "Legs/regular_legs.png",
		"displayname" : "Regular Legs",
		"details" : "Normal person's legs",
		"prerequisite" : ["regular_leg2"],
		"part_level" : 3,
		"part_dmg" : 0,
		"part_hp" : 0,
		"part_speed" : 0,
		"part_def" : 0,
		"drop_loc" : "forest"
	},
}
